/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.player;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    
}
